### PR TITLE
updated survey_data

### PR DESCRIPTION
**Pull request by casstai**
add a bunch of surveys. @fsolt please check the file. I haven't tested it yet and not sure whether my addition is right.

### CODE REVIEW

**Comment by fsolt** [comment]
What are the cb files listed at 183-191?  Do you have a download link for them (to include in `data_link`)?

**Comment by fsolt** [comment]
Similarly the `lits` files at 565-567?

**Comment by fsolt** [comment]
I note, fyi, that all the data in nbb_combo (New Baltic Barometer) file is already in neb_combo (New Europe Barometer).

**Comment by Tyhcass** [comment]
> What are the `cb` files listed at 183-191? Do you have a download link for them (to include in `data_link`)?

link: https://caucasusbarometer.org/en/downloads/
 Life in Transition Survey (LITS) list: https://www.ebrd.com/what-we-do/economic-research-and-data/data/lits.html

**Comment by Tyhcass** [comment]
> I note, fyi, that all the data in nbb_combo (New Baltic Barometer) file is already in neb_combo (New Europe Barometer).

I remembered I saw that information, but not sure whether they include all NBB or just the latest ones. So, all NBB?

**Comment by fsolt** [comment]
I double-checked: the NEB has all of NBB.  I'm in favor of keeping "duplicate" stuff in `survey_data`, so no big deal, so long as you don't accidentally put both in the same project's `surveys` file

**Comment by Tyhcass** [comment]
Gotcha. I will delete NBB entries in survey files.

**Comment by Tyhcass** [comment]
Regarding the added new surveys, like lits, I messed up the archive, survey, and file columns...

**Comment by fsolt** [comment]
I caught this issue with `lits` and `cb` (which I've renamed `caucasusb`, because otherwise I'd never know what survey that is).  I didn't see any others.  Did you have any others in mind?

**Comment by Tyhcass** [comment]
Regarding Carnegie Middle East Governance and IslamDataset,1988-2014, it is an integrated dataset, and WVS and Arab barometer are included. So, we need to filter out WVS and Arab barometer, is that right?

**Comment by Tyhcass** [comment]
So far, just found the issue with lits and cb. Most of the others can be downloaded from existing archives.

**Comment by fsolt** [comment]
> Regarding Carnegie Middle East Governance and IslamDataset,1988-2014, it is an integrated dataset, and WVS and Arab barometer are included. So, we need to filter out WVS and Arab barometer, is that right?


The only part of that project that has surveys not included elsewhere is `tcmeg2004`

**Comment by fsolt** [comment]
> So far, just found the issue with lits and cb. Most of the others can be downloaded from existing archives.

That's what I have found, too.

**Comment by fsolt** [comment]
> > Regarding Carnegie Middle East Governance and IslamDataset,1988-2014, it is an integrated dataset, and WVS and Arab barometer are included. So, we need to filter out WVS and Arab barometer, is that right?
> 
> The only part of that project that has surveys not included elsewhere is `tcmeg2004`

Okay, looking again `tcmeg2004` is the whole thing, but I remember how it works now: it is basically a wide-formatted dataset, with variables identified by what survey and year they are asked in.  So as long as you include only the questions that are distinctive--i.e., not WVS, etc.--you are fine.

**Comment by Tyhcass** [comment]
Hi Fred, again, as for Carnegie Middle East Governance and IslamDataset,1988-2014,  the dataset I downloaded is not wide-formatted.  So, we might have differently formatted data? Might I have your data if it is wide-formatted? 
image

**Comment by Tyhcass** [comment]
14=eg&ku1988 
15=pa1995 
16=pa1999  So do we need to include these three early surveys?

**Comment by fsolt** [comment]
eg&ku1988 are not national surveys; they only cover the capital city.  I forget why I decided against pa1995 & 1999, tbh, but I'm sure I had some reason

**Comment by Tyhcass** [comment]
Regarding vpcpce, all file_ids are the same one? UKDA-4129-stata6? All individual data has been aggregated via DCPO? However, there is no county variable. I would like to have public surveys.

**Comment by fsolt** [comment]
I've fixed the `surveys_data` file for vpcpce (the `subfile` column is for stuff just like this).  I'll email you an R script that finishes off processing the vpcpce files, Cassandra.

**Comment by Tyhcass** [comment]
Fred, I met some problems when applying dcpo_setup.

I failed to set up tcmeg2004, and the warning message is "In eval(substitute(expr), data, enclos = parent.frame()) ".  
When I tried ess and evs data, including ess_combo, evs_combo, evs1999ger, evs1999fin,	and evs1999tu,  the result is null and the warning message is "Error in if (!is.na(ds$subfile)) dataset_file <- paste0(ds$subfile, ".RData") : argument is of length zero". However, there is no subfile values for these dataset.
Thanks.

**Comment by Tyhcass** [comment]
It turns out that there are a bunch of dataset meet the "if (!is.na(ds$subfile)) dataset_file <- paste0(ds$subfile, ".RData") " problems. I think ALL of them are from the dataset which I added. However, I cannot figure out which part I did wrong.

**Comment by fsolt** [comment]
I could stand to write  into this code some checks for common problems, with helpful error messages, but I haven't.  Anyway, I've found that "Error in if (!is.na(ds$subfile)) dataset_file <- paste0(ds$subfile, ".RData") : argument is of length zero" almost always means that I haven't entered the data into DCPOtools yet (most of the time, but probably not in your cases; I assume you've updated from the repo recently) or downloaded it correctly:

0. Is the dataset in DCPOtools?
1. Is the dataset located at `archive`_file/`surv_program`_file/`file_id`?
2. Has the dataset at that location been converted to RData format, with the `.RData` extension?

I do note that `evs1999ger` is in `evs_combo`.  Is this one of the cases where not all of the questions were included?

The error you got for tcmeg2004 doesn't look familiar at all.  In that case, I'd walk through the `dcpo_code` line by line to see where the problem is.

**Comment by Tyhcass** [comment]
A, update DCPOtools..  I haven't done it!

**Comment by fsolt** [comment]
Yay!  Successful debugging!

**Comment by Tyhcass** [comment]
Yeah, after updating DCPOtools, the "subfile" problem is solved!!!!! Yes, you are right, evs1999ger is in combo. Thanks!!

**Comment by Tyhcass** [comment]
I have set up most datasets, except the following ones. 

For tcmeg2004, the warning message is  "Error in `$<-.data.frame`(`*tmp*`, "wt_dcpo", value = 1) : 
  replacement has 1 row, data has 0
In addition: Warning messages:
1: Problem with `mutate()` input `modal_year`.
i no non-missing arguments to max; returning -Inf
i Input `modal_year` is `as.integer(...)`. 
2: In max(table(t_data[[ds$year_var]])) :
  no non-missing arguments to max; returning -Inf

For lits_wave3 and caucasusb2008,  the error is  "Can't transform a data frame with duplicate names." 

I also got the warning message " Unknown or uninitialised column: `isocntry`. "  Does it matter?  Here, "isocntry" is in self-defined weight. 

I am going to update survey_data by adding one dataset and correcting several typos. If these warnings are not caused by survey_data, I will pull the survey_data after updating.

**Comment by fsolt** [comment]
Updated `DCPOtools` fixes problem with lits_wave3 and caucasusb2008
Screen Shot 2021-04-02 at 9 41 06 AM

**Comment by fsolt** [comment]
You're getting the error from `tcmeg2004` because the trust questions don't appear to have been asked in the unique NSF surveys (`msurvey==2`).  At least `m301c`, trust in parliament, wasn't.  Hence, no rows in the dataset.

**Comment by Tyhcass** [comment]
@fsolt  caucasusb2008 works, but the problem is still there for lit_wave3.  Also, could you please check and approve the survey_data I pulled yesterday? I am so close to setup the dataset. Yeah!!!! Thanks.

**Comment by Tyhcass** [comment]
Wait, my fault. It works for lit_wave3 too... Now, just surveys_data.

**Comment by Tyhcass** [comment]
> msurvey==

I double-checked there are values for trust item in tcmeg2004. Actually, the problem is that when we load RData (converted from rda), the values for variable "msurvey" are not numbers. However, if the dta file works, so, we might convert dta to RData.  @fsolt   

image

**Comment by fsolt** [comment]
I looked at the data in Stata, and didn't see any `m301c` with `msurvey==2`

**Comment by fsolt** [comment]
And if you could fix the conflicts in your PR, that would be a help

**Comment by Tyhcass** [comment]
> I looked at the data in Stata, and didn't see any `m301c` with `msurvey==2`
image

**Comment by fsolt** [comment]
Oops, my mistake--clicked on MDATASET instead of MSURVEY, and it didn't register in my head.  Perils of non-scripting.  Sorry about that.

**Comment by fsolt** [comment]
Yeah, actually, I don't have any problem with `tcmeg2004` at all:
Screen Shot 2021-04-03 at 9 34 53 AM

**Comment by fsolt** [comment]
Did you use `get_surveys` to download and convert `tcmeg2004`?

**Comment by Tyhcass** [comment]
> Did you use `get_surveys` to download and convert `tcmeg2004`?

A, that might be the problem. I will redownload it via "get_surveys" right away.

**Comment by fsolt** [comment]
Here's the important part.  You can paste in your filepath to fix:

```
        tryCatch(rio::convert(file.path(new_dir2, data_file),
                              str_replace(file.path(new_dir, data_file), ".dta", ".RData")),
                 error = function(c) suppressWarnings(
                   foreign::read.dta(file.path(new_dir2, data_file),
                                     convert.factors = FALSE) %>%
                     rio::export(str_replace(file.path(new_dir, data_file), ".dta", ".RData"))
                 )
```

**Comment by fsolt** [comment]
Or, you're probably right that's it's probably easier to just re-download.

**Comment by Tyhcass** [comment]
It works now!! However, when I used "convert", country names are number not characters.  I didn't figure out the reasons.  Finally, convert it by hand.....

**Comment by fsolt** [comment]
Yeah, that’s the way the data comes.  `dcpo_setup` deals with that.


From: Tyhcass ***@***.***>
Date: Saturday, April 3, 2021 at 11:00 AM
To: fsolt/DCPOtools ***@***.***>
Cc: Solt, Frederick ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [fsolt/DCPOtools] updated survey_data (#43)

It works now!! However, when I used "convert", country names are number not characters. I didn't figure out the reasons. Finally, convert it by hand.....

**Pull request closed without merging**
